# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(max_length=30),
        ),
    ]
