# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_remove_rate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='award.Project'),
        ),
    ]
