# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20181018_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
