# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_rate_creativity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='creativity',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
